------------------------------10:52:37------------------------------
Mensagem de Erro:-> Referência de objeto não definida para uma instância de um objeto.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
<=
Pilha de Execução:->    em System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   em System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   em Repositorios.Repositorio.MontarObjetoDoReaderSemRead[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 297
   em Repositorios.Repositorio.MontarObjetoDoReader[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 62
   em Repositorios.ConexaoBancoSqlServer.ExecutarConsultaObject[TObject](IDbCommand command, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\ConexaoBancoSqlServer.cs:linha 109
   em Repositorios.RepositorioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\RepositorioCartaoIdentificacao.cs:linha 175
   em Negocios.NegocioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Negocios\NegocioCartaoIdentificacao.cs:linha 33
   em Servicos.Fachada.ObterCartaoIdentificacaoPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Servicos\Fachada.cs:linha 311<=
Classe da Exceção:-> TargetInvocationException<=
Origem da Exceção:-> mscorlib<=
==============================10:52:37==============================
------------------------------10:52:43------------------------------
Mensagem de Erro:-> Tentativa inválida de chamar MetaData quando o leitor estava fechado.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
<=
Pilha de Execução:->    em System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   em System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   em Repositorios.Repositorio.MontarObjetoDoReaderSemRead[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 297
   em Repositorios.Repositorio.MontarObjetoDoReader[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 62
   em Repositorios.ConexaoBancoSqlServer.ExecutarConsultaObject[TObject](IDbCommand command, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\ConexaoBancoSqlServer.cs:linha 109
   em Repositorios.RepositorioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\RepositorioCartaoIdentificacao.cs:linha 175
   em Negocios.NegocioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Negocios\NegocioCartaoIdentificacao.cs:linha 33
   em Servicos.Fachada.ObterCartaoIdentificacaoPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Servicos\Fachada.cs:linha 311<=
Classe da Exceção:-> TargetInvocationException<=
Origem da Exceção:-> mscorlib<=
==============================10:52:43==============================
------------------------------10:58:59------------------------------
Mensagem de Erro:-> Referência de objeto não definida para uma instância de um objeto.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
<=
Pilha de Execução:->    em System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   em System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   em Repositorios.Repositorio.MontarObjetoDoReaderSemRead[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 297
   em Repositorios.Repositorio.MontarObjetoDoReader[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 62
   em Repositorios.ConexaoBancoSqlServer.ExecutarConsultaObject[TObject](IDbCommand command, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\ConexaoBancoSqlServer.cs:linha 109
   em Repositorios.RepositorioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\RepositorioCartaoIdentificacao.cs:linha 175
   em Negocios.NegocioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Negocios\NegocioCartaoIdentificacao.cs:linha 33
   em Servicos.Fachada.ObterCartaoIdentificacaoPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Servicos\Fachada.cs:linha 311<=
Classe da Exceção:-> TargetInvocationException<=
Origem da Exceção:-> mscorlib<=
==============================10:58:59==============================
------------------------------11:02:19------------------------------
Mensagem de Erro:-> Referência de objeto não definida para uma instância de um objeto.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
<=
Pilha de Execução:->    em System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   em System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   em Repositorios.Repositorio.MontarObjetoDoReaderSemRead[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 297
   em Repositorios.Repositorio.MontarObjetoDoReader[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 62
   em Repositorios.ConexaoBancoSqlServer.ExecutarConsultaObject[TObject](IDbCommand command, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\ConexaoBancoSqlServer.cs:linha 109
   em Repositorios.RepositorioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\RepositorioCartaoIdentificacao.cs:linha 175
   em Negocios.NegocioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Negocios\NegocioCartaoIdentificacao.cs:linha 33
   em Servicos.Fachada.ObterCartaoIdentificacaoPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Servicos\Fachada.cs:linha 311<=
Classe da Exceção:-> TargetInvocationException<=
Origem da Exceção:-> mscorlib<=
==============================11:02:19==============================
------------------------------11:09:25------------------------------
Mensagem de Erro:-> Referência de objeto não definida para uma instância de um objeto.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
Uma exceção foi acionada pelo destino de uma chamada.
<=
Pilha de Execução:->    em System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   em System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   em Repositorios.Repositorio.MontarObjetoDoReaderSemRead[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 297
   em Repositorios.Repositorio.MontarObjetoDoReader[TObject](IDataReader dataReader, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\Repositorio.cs:linha 62
   em Repositorios.ConexaoBancoSqlServer.ExecutarConsultaObject[TObject](IDbCommand command, TObject objeto, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\ConexaoBancoSqlServer.cs:linha 109
   em Repositorios.RepositorioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Repositorios\RepositorioCartaoIdentificacao.cs:linha 175
   em Negocios.NegocioCartaoIdentificacao.ObterPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Negocios\NegocioCartaoIdentificacao.cs:linha 33
   em Servicos.Fachada.ObterCartaoIdentificacaoPorCodigo(String codigo, Boolean lazy) na c:\Arquivos_UNIMED\Dev_Projetos\C#\LibrayUnimedVsfCSharp\Servicos\Fachada.cs:linha 311<=
Classe da Exceção:-> TargetInvocationException<=
Origem da Exceção:-> mscorlib<=
==============================11:09:25==============================
